apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-rules
  namespace: kube-system
  labels:
    app: prometheus
    component: rules
data:
  coredns.rules: |
    groups:
    - name: coredns.rules
      rules:
      - record: coredns:dns_request_duration_seconds:quantile5m
        expr: histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{k8s_app="kube-dns"}[5m])) by (le, instance))
        labels:
          quantile: "0.99"
      - alert: DNSResponseLatencyHigh
        expr: coredns:dns_request_duration_seconds:quantile5m{quantile="0.99"} > 0.075
        labels:
          service: platform
          severity: critical
        annotations:
          description: CoreDNS on `{{ $labels.instance }}` has a 99th percentile response latency of {{ $value | humanize }}s
