apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: auth
data:
  oauth2.conf: |
    client_id="oauth2-proxy"
    cookie_domain=".icelyn.io"
    cookie_name="IcelynKubernetesOAuth{{- if eq .ClusterImageLifecycleTag `staging` -}}Staging{{- end -}}"
    cookie_secure="true"
    cookie_expire="168h"
    cookie_refresh="15m"
    email_domains="icelyn.com"
    http_address="0.0.0.0:80"
    pass_access_token="true"
    provider="oidc"
    whitelist_domains=".icelyn.io"
    scope="openid profile email groups audience:server:client_id:kubernetes offline_access"
    set_authorization_header="true"
