kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: auth
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - oauth2-proxy
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
        - name: oauth2-proxy
          image: oauth2-proxy
          ports:
            - containerPort: 80
              protocol: TCP
          args:
            - --config=/etc/oauth2/oauth2.conf
            - --cookie-secret=$(cookie_secret)
            - --client-secret=$(client_secret)
            - --oidc-issuer-url=https://$(issuer_host)/dex
            - --redirect-url=https://$(issuer_host)/oauth2/callback
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /etc/oauth2/oauth2.conf
              subPath: oauth2.conf
            - name: certificates
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          env:
            - name: issuer_host
              value: "auth{{- if eq .ClusterImageLifecycleTag `staging` -}}-staging{{- end -}}.icelyn.io"
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: client-secret
            - name: cookie_secret
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: cookie-secret
      volumes:
        - name: config
          configMap:
            name: oauth2-proxy
        - name: certificates
          hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
      serviceAccountName: oauth2-proxy
