kind: Service
apiVersion: v1
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: auth
spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30093
  selector:
    app: oauth2-proxy
