---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-ingress-controller
  namespace: monitoring
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx-ingress
      component: controller
