apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: monitoring
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      nodePort: 30090
  selector:
    app: nginx-ingress
    component: controller
