apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth
data:
  config.yaml: |
    issuer: https://%issuer_host%/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:80
    connectors:
    - type: google
      id: google
      name: Google
      config:
        issuer: https://accounts.google.com
        clientID: %google_client_id%
        clientSecret: %google_client_secret%
        redirectURI: https://%issuer_host%/dex/callback
        hostedDomains:
        - icelyn.io
        serviceAccountFilePath: /etc/dex/service-account.json
        adminEmail: oidc@icelyn.io
    oauth2:
      skipApprovalScreen: true

    expiry:
      signingKeys: "2h"
      idTokens: "15m"

    staticClients:
    - id: kubernetes
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      name: 'Kubernetes API'
      secret: %kubernetes_client_secret%
      trustedPeers:
      - oauth2-proxy
    - id: oauth2-proxy
      redirectURIs:
      - https://%issuer_host%/oauth2/callback
      name: 'OAuth2 Proxy'
      secret: %oauth2_client_secret%
    enablePasswordDB: false
