kind: Service
apiVersion: v1
metadata:
  labels:
    app: dex
  name: dex
  namespace: auth
spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30092
  selector:
    app: dex
