apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-proxy
  namespace: kube-system
  labels:
    app: sealed-secrets
rules:
- apiGroups:
  - ""
  resourceNames:
  - "http:sealed-secrets-controller:"
  resources:
  - services/proxy
  verbs:
  - get
